import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '../components/sidebar/page'
import Appbar from '../components/appbar/page'
import Footer from '../components/footer/page'
import ReduxProvider from '@/hooks/provider'
import { ThemeProvider } from '@mui/material'
import theme from '../global/theme'
import LoadAdsense from '@/components/adsense/loadAdsense'
import Script from 'next/script'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Eagle News',
  description: 'Generated by Eagle News',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ThemeProvider theme={theme}>

      <html lang="en">
        <body className={inter.className}>
          <ReduxProvider>
            <Appbar />
            {children}
            <Footer />
          </ReduxProvider>

        </body>
      </html>
    </ThemeProvider>
  )
}
